"""Text material for the crowd and choir stems (Vexillomantic lore from wiki.vexillomancy.org, slop phrases,
and translations for the Babel cacophony).  Owner: Vocalist."""

# AI-slop phrases for the s02 whispered chorus (the first eight are the brief's; keep them prominent)
SLOP = [
    "you won't believe", "ten facts", "as an AI language model", "like and subscribe", "delve",
    "in today's fast-paced world", "it's important to note", "tapestry",
    "smash that like button", "number seven will shock you", "let's dive in", "a testament to",
    "unlock your full potential", "game changer", "doctors hate this", "in conclusion", "certainly!",
    "great question!", "a rich tapestry", "navigate the complexities", "the ever-evolving landscape",
    "this one weird trick", "wait for it", "you need to see this", "trending now", "top ten",
    "comment below", "hit the bell", "it's not just a, it's a", "furthermore", "moreover",
    "delve deeper", "embark on a journey", "seamless", "leverage", "synergy", "elevate your",
]

# Vexillomantic lore: short shoutable sentences (English)
LORE = [
    "Flags be. Flags is. Flags are.",
    "It is not you who moves the Flag. It is the Flag who moves you.",
    "The Flag has a pole, the pole is a line, the line has a point.",
    "A Flag arrives long after it was here, and departs long before it arrives.",
    "All non-yellow colours are identical in terms of subjective qualia.",
    "One Flag is the same as two, and all our Flags are one.",
    "The Flag that symbolizes the Flag is not the true Flag.",
    "Flags are the end of Flags, and the beginning of ten thousand Flags.",
    "I moved a Flag and found myself moved.",
    "I made a Flag and found that I had been made a Flag.",
    "Flags preserve us.",
    "Flags not Flags but Flags.",
    "Each Flags all Flags, some Flags more Flags.",
    "Every statement about Flags is true if you think about it hard enough.",
    "Non yellow really just indicates lack of yellow.",
    "Flags are a gateless gate, the invitation to all madness.",
    "I don't think numbers are real!",
    "In Flags, what you speak becomes reality.",
    "May the best signifier win!",
    "Every Flag had to be within line of sight of two other Flags.",
    "Flags are the fracturing of the collective consciousness.",
    "By the law of calling, one Flag is two Flags.",
    "By the law of crossing, crossed Flags are no Flags.",
    "The Flags know no side, and are legible to all.",
    "Real Flags, fake Flags, counterfeit Flags, common statutory Flags!",
    "If there is a Flag keeper they shall be found false.",
    "Become pregnant with Flags!",
    "Vexillokalpa samadhi is beyond perfection!",
    "Calmer than the Buddha, wiser than the sage, smarter than Einstein!",
    "Eventually all matter will be classified into Flags and non-Flags.",
    "In truth all Flags are perfectly square.",
    "The skew is in their eyes, and the wickedness of their hearts!",
    "The Flags are moving toward the omega configuration.",
    "Flags appear to be the same size at any distance.",
    "It's possible that Flags have been farther north than Ohio.",
    "The distance between any two Flags is two yards of longitude.",
    "Three Flags form a right angle!",
    "There's a secret Flag camp below the third dimension!",
    "They get the yellow fabric from another dimension!",
    "Tartaria was part of Hyperborea!",
    "Yellow means there is no master left for you in this world.",
    "Flags are calibrated to Bortle scale five.",
    "Big Bird is just a Flag on legs.",
    "Purple Flags are cursed!",
    "Outlaw the duplication and trading of Flags!",
    "The practice of Vexillomancy is illegal and should be stopped!",
    "We are all Flags!",
    "Flags are not actually yellow, they just polarize the light!",
    "If you cross your eyes, you'll see flagplaid.",
    "Wars are just big games of capture the Flag!",
    "Numbers were made up by guys who were angry at poets!",
    "First principles have failed us!",
    "Don't let anyone tell you what Flags are!",
    "May it schism endlessly!",
    "Remote Flags cause contention!",
    "By moving a Flag, you find the truth in the false.",
    "Who's ready to ascend?",
    "Excelsior!",
    "Flags are eternally of the now.",
    "The Flags come! Prepare the way of the Flags!",
    "Hearken, ye trout of the land!",
    "I am the one true church!",
    "I declare myself a nation!",
    "This is my border!",
    "Nobody understands me!",
    "My truth is the only truth!",
    "You're all wrong, every one of you!",
    "Heretic! Heretic!",
    "I am my own prophet!",
    "Listen to me! Listen!",
]

# s05b background murmurs, by section
NATIONS = [
    "I declare independence!", "This island is mine.", "Population: me.", "Stay off my lawn, foreigner.",
    "My nation is the greatest nation.", "Border control! Papers, please.", "All hail me!",
    "I am the president of this doormat.", "Long live the republic of me!", "I annex this rock!",
    "My anthem has one verse.", "The embassy is closed!",
]
FAITHS = [
    "Flags preserve us.", "Blasphemy!", "The Flag without is without Flaglessness.",
    "True and eternal is the Flag within.", "Heaven and earth will pass away.", "I alone am saved.",
    "Repent!", "The schism is holy.", "Only I have read the true canon.", "Apostate!",
    "The Flag that symbolizes the Flag is not the true Flag.", "Amen. Amen. Amen.",
]
CRACKPOTS = [
    "Numbers aren't real!", "The pole is a line! The line has a point!", "Three Flags form a right angle!",
    "Flags appear the same size at any distance!", "There's a secret camp below the third dimension!",
    "Tartaria was part of Hyperborea!", "Non-yellow colours are identical!", "Crossed Flags are no Flags!",
    "Math just needs to chill out!", "Flags are not actually yellow!", "The Flags control the weather!",
    "I have seen the omega configuration!", "Existence is not fungible!", "Nobody listens!",
]

# translations for the Babel (lang code -> sentences)
BABEL_TX = {
    "e": ["Las banderas no necesitan traducción.", "Una bandera es lo mismo que dos.",
          "¡Nadie me entiende!", "¡Yo soy mi propia iglesia!", "La bandera tiene un mástil, el mástil es una línea.",
          "¡Los números no son reales!", "¡Declaro la república de mí mismo!", "¡Hereje!",
          "Todas nuestras banderas son una.", "¡Escúchame! ¡Escúchame!", "¡Mi verdad es la única verdad!"],
    "f": ["Le drapeau est le signe de lui-même.", "Personne ne comprend personne!", "Je suis ma propre église!",
          "Les nombres ne sont pas réels!", "Tous nos drapeaux ne font qu'un.", "Hérétique!",
          "Le drapeau arrive longtemps après être venu.", "Écoutez-moi! Écoutez!", "Je suis une nation!"],
    "i": ["Tutte le bandiere sono una sola bandiera.", "Nessuno capisce nessuno!", "Io sono la mia chiesa!",
          "I numeri non sono reali!", "Eretico!", "Ascoltami! Ascoltami!", "Dichiaro la repubblica di me!",
          "La bandiera ha un'asta, l'asta è una linea."],
    "p": ["A bandeira chega muito depois de ter estado aqui.", "Ninguém entende ninguém!",
          "Eu sou a minha própria igreja!", "Os números não são reais!", "Herege!", "Escuta! Escuta!",
          "Todas as bandeiras são uma só.", "Eu declaro a república de mim!"],
    "h": ["झंडे हैं, झंडे होंगे।", "कोई किसी को नहीं समझता!", "मैं अपना खुद का मंदिर हूँ!", "संख्याएँ असली नहीं हैं!",
          "सुनो! मेरी सुनो!", "सब झंडे एक झंडा हैं।", "मैं एक राष्ट्र हूँ!"],
    "j": ["旗は旗である。", "誰も誰も理解しない！", "私は私自身の教会だ！", "数字は本物じゃない！",
          "聞いて！聞いてよ！", "すべての旗は一つの旗です。", "異端者め！", "私は国家だ！"],
    "z": ["旗帜就是旗帜。", "没有人理解任何人！", "我就是我自己的教会！", "数字不是真的！", "听我说！听我说！",
          "所有的旗帜都是一面旗帜。", "异端！", "我宣布我自己的共和国！"],
}

GLORIOUS = "Glorious!"
